M48
; DRILL file {KiCad 7.0.11} date Tue May 28 23:21:34 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-05-28T23:21:34+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0610
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1378
%
G90
G05
T1
X6.2984Y-5.9889
X7.2535Y-5.9889
T2
X4.1644Y-4.0964
X4.1644Y-6.2576
X7.8416Y-4.0964
X7.8416Y-6.2576
M30
